// <auto-generated />
using CryptoCoins;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoCoins.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220115093912_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CryptoCoins.Entities.Coins", b =>
                {
                    b.Property<int>("CoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CoinName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoinValue")
                        .HasColumnType("float");

                    b.HasKey("CoinId");

                    b.ToTable("CryptoCoins");
                });
#pragma warning restore 612, 618
        }
    }
}
