apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: crypto-coins-qa-app
    app.kubernetes.io/instance: crypto-coins-qa-app-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: crypto-coins-qa-app
spec:
  selector:
    app: crypto-coins-qa-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
